
# html lang
language: zh

# main menu navigation
menu:
  首页: /poker/
  归档: /poker/archives

# Miscelaneous
favicon: /

# stylesheets loaded in the <head>
stylesheets:
- /poker/css/meeseeks.css

# scripts loaded in the end of the body
scripts:
- /poker/js/meeseeks.js
