
# html lang
language: zh

# main menu navigation
menu:
  首页: /blog/
  归档: /blog/archives/

# Miscelaneous
favicon: /

# stylesheets loaded in the <head>
stylesheets:
- /blog/css/meeseeks.css

# scripts loaded in the end of the body
scripts:
- /blog/js/meeseeks.js
