
# html lang
language: zh

# main menu navigation
menu:
  首页: /pokerhub/
  归档: /pokerhub/archives/

# Miscelaneous
favicon: /

# stylesheets loaded in the <head>
stylesheets:
- /pokerhub/css/meeseeks.css

# scripts loaded in the end of the body
scripts:
- /pokerhub/js/meeseeks.js
